### ISSUE TITLE
Option to maximise dialog

### ISSUE THREAD

**Issue by Synchro** [makeusabrew/bootbox#190]
This is a feature request. I've tried various means of maximising dialogs (taking up the full window size minus a small margin so it's still apparent it's a modal) for page previews, in-page reports etc with bootstrap with mixed success. I'd really like to be able to do all my dialogs with bootbox, and that's the only use case I'm currently using (not very pretty) custom code for.

**Comment by snimavat** [comment]
is there an option now to specify maximum height ? - cant find it in docs

**Comment by tiesont** [comment]
No, there isn't. If you're using Bootbox 5 and Bootstrap 4.3.0 or newer, there is a `scrollable` option I added to allow you to take advantage of the `modal-dialog-scrollable` class, which automatically makes the modal's content scrollable. http://bootboxjs.com/documentation.html#bb-option-scrollable

Otherwise, you can handle this yourself by using the `className` property and adding your own CSS rules for constraining the modal body, which is what I used to do before that option became available.
