### ISSUE TITLE
bootbox custom dialog close with outside click?

### ISSUE THREAD

**Issue by tdmoneybanks** [makeusabrew/bootbox#402]
Hi, I noticed your comment in #395 and put an onEscape callback along with my dialog. Now clicking the escape works but clicking on the backdrop still does not. How would I get the backdrop click to also dismiss it? note: I have also set backdrop: true and no results.

**Comment by makeusabrew** [comment]
First of all make sure you're definitely using 4.4.0; that was the first release to support `backdrop`. If things still don't work then if you could post a link to an example (on jsFiddle or similar) that'd be great.

For what it's worth I just put this into the console on the bootboxjs.com site and it worked okay:

```bootbox.dialog({
  message: "hi",
  onEscape: function() { console.log("Escape!"); },
  backdrop: true
})
```

Cheers,

Nick

**Comment by tdmoneybanks** [comment]
ahh ok. so I am using a meteor package to add bootbox and it appears to be version 4.3. Do you happen to know any way to do the same functionality using 4.3? 
Thanks a lot,
Tyler

**Comment by makeusabrew** [comment]
I'm afraid not. Although an oft-requested feature it only made its way in with 4.4.0 and isn't really easy to patch in yourself for 4.3.0. Out of interest which package is it you're using? Might be worth giving the maintainer a nudge :)

**Comment by tdmoneybanks** [comment]
I actually had the same idea ha. So, currently, I am using this one https://atmospherejs.com/mizzao/bootboxjs which is obviously the most popular. However, its clear looking at the history that updating stopped after august '14 on v4.3.0. There is another package that seems to be 4.4.0 here https://atmospherejs.com/cwohlman/bootboxjs but its obviously not used by many people.

**Comment by makeusabrew** [comment]
In defence of the first package, there was a *huge* gap between 4.3.0 and 4.4.0, so a last published date of August '14 doesn't necessarily mean it's been abandoned. It appears its maintainer is on GitHub, so let's ping @mizzao and see what happens :)

**Comment by tarlepp** [comment]
@tdmoneybanks could you use ```bower``` for installing this?

**Comment by tdmoneybanks** [comment]
True I doubt its been actually abandoned. He seems to have a lot of projects so probably just busy. @tarlepp I suppose I could but i'm not sure what benefit that will give me over installing it with 
    meteor add
why do you suggest I use bower as opposed to meteor's package manager?

**Comment by tarlepp** [comment]
Bower is more commonly used package manager for js libraries. Seems like that Meteor package manager needs some custom stuff to each library, eg. those bootbox.js libraries. Wouldn't it be easier to just use https://atmospherejs.com/mquandalle/bower and then pure bower packages.

**Comment by mizzao** [comment]
I've been pinged! Why don't you just send a PR for 4.4.0 or open an issue?

**Comment by tdmoneybanks** [comment]
@tarlepp does using bower and also some meteor packages in the same project have the potential for dependency problems? 
@mizzao sorry about that! I didn't notice your package was 4.3.0 until after opening this. Thought it was a problem within my code:)

**Comment by tarlepp** [comment]
Hmm, is that  ```package.js``` only thing that meteor package needs? If so, could you guys think to add this to official bootbox repo? In this way there is no need to maintain multiple repos of same thing.

**Comment by mizzao** [comment]
@tarlepp `package.js` is needed, and also someone needs to `meteor publish author:bootboxjs` after each release (or you could use a hook: http://autopublish.meteor.com/).

**Comment by tarlepp** [comment]
Ok, so I think that's the best solution then? If I remember correct there was same situation with bower a while ago, someone other maintained that repo and it was always out-of-dated.

@makeusabrew What do you think?

**Comment by vcarel** [comment]
ok, there's still an issue on 4.4.0 there.

Let me summarize:
- backdrop undefined : the backdrop is displayed, but clicking on it has no effect
- backdrop=true: the backdrop is displayed and clicking on it dismisses the dialog
- backdrop=false: the backdrop is not displayed

I think dismiss actions should be completely decorrelated from the appearance of the backdrop.
And dimiss actions such as Escape key or Click-Outside should be enabled by default, along with that little cross icon in the top-right corner. I believe 99.9 % of the users would not prevent users to dismiss by pressing Escape or Click Outside.

**Comment by makeusabrew** [comment]
@vcarel point taken, but:

* Bootbox exists primarily to replicate `window.alert`, `window.confirm` and `window.prompt` calls using Bootstrap's modals. Whenever there's a grey area over UX, it takes its steer from their behaviour. These native methods do not allow the users to 'click away', but they do allow users to press escape to dismiss them. That's why Bootbox behaves the same way by default
* The `backdrop` behaviour now works according to Bootstrap's documentation which a lot of users had requested. The only 'surprise' is that not passing it will default it to using Bootstrap's `static` option (i.e. can't dismiss by clicking outside the modal). However, this has to be the default as otherwise 4.4.0 would have broken backward compatibility and had to be 5.0.0 instead.

**Comment by vcarel** [comment]
The functions window.alert, confirm and prompt are almost 20 years old. You can't assume that they are an example of good UX. I would *never* put an alert on a web application. I'm using modals on purpose, and it's not only because it looks nicer, but also because I get more control on the UX I want to provide.

**Comment by makeusabrew** [comment]
> The functions window.alert, confirm and prompt are almost 20 years old. You can't assume that they are an example of good UX.

Good UX or not (which I think depends on context), Bootbox's raison d'être is to mimic these methods. Indeed, the project's strapline is still _"Wrappers for JavaScript alert(), confirm() and other flexible dialogs using Twitter's bootstrap framework"_ and has been since 2011, so I think this default behaviour is still acceptable.

> I would never put an alert on a web application. I'm using modals on purpose, and it's not only because it looks nicer, but also because I get more control on the UX I want to provide.

Sure; and you have that control :). You can just set the `backdrop` property when invoking a modal. As I said, creating a whole new major version just to invert some default behaviour which has been in place for four years is a big overhead to maintain and will confuse users (who'll expect loads of cool new features for a major release). I honestly don't see the problem.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
