### ISSUE TITLE
backdrop option is not passed properly

### ISSUE THREAD

**Issue by laoshanlung** [makeusabrew/bootbox#408]
I am using the latest version of bootbox and bootstrap 3.0.3. I set `backdrop` to `true` so that the dialog can be dismissed by clicking the grey background. Apparently, it does not work so I take a look at the source code and find this.

https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L738
```
    dialog.modal({
      backdrop: options.backdrop ? "static": false,
      keyboard: false,
      show: false
    });
```

If I understand javascript correct (which I doubt that I can ever do it), even if you set `options.backdrop` to `true` at the end it is still passed to boostrap modal as `static`

Are there any special reasons for doing it that I am not aware of?

Not related: Are there any special reasons that `keyboard` is fixed to `false` instead of letting people passing their own options?

P/s: If there are no special reasons to the 2 questions above, I can submit a pull request

**Comment by makeusabrew** [comment]
We always pass `static` as otherwise we can't trap the relevant event when the user clicks outside the modal. See the comments here:

https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L677-L684

Regardless of what Bootbox has to do internally, the options presented to the user should work as expected. If it's not, that's a bug :). Could you submit a jsFiddle link or similar so I can take a look please?

The same justification exists for `keyboard` - we already support closing the dialog by pressing the escape key but the difference is with a Bootbox dialog this needs to be accompanied by an `onEscape` callback. Simply allowing `keyboard: true` would mean the dialog could be dismissed without ever triggering a callback.

**Comment by laoshanlung** [comment]
My setup is
- Bootstrap 3.0.3
- jQuery 2.0.2
- Bootbox 4.3.0 (I want to use the latest 4.4.0 but CDNJS doesn't have it)

http://jsfiddle.net/5306ork5/

Normally, in Bootstrap Modal when I set `backdrop` to true, I am able to click on the background to hide the modal

**Comment by makeusabrew** [comment]
@laoshanlung sorry, missed your update. `backdrop` support was only rolled out in 4.4.0.
