### ISSUE TITLE
Two modals appear

### ISSUE THREAD

**Issue by quillford** [makeusabrew/bootbox#416]
When I use bootbox for making modals, it looks like this. 
Bootstrap version: v3.2.0
![mousse](https://cloud.githubusercontent.com/assets/8762862/7095389/ec0d1ade-df7e-11e4-965e-077deff7f197.png)

**Comment by quillford** [comment]
I think I found the issue. It seems to be an issue with the modal-dialog class.

Before: 
![mousse 2](https://cloud.githubusercontent.com/assets/8762862/7095763/e0bf01a8-df81-11e4-8c84-d89e28708412.png)
After:
![mousse 3](https://cloud.githubusercontent.com/assets/8762862/7095767/e5d34276-df81-11e4-8ad9-ee37f85add76.png)

**Comment by tarlepp** [comment]
weird, could you make a plunker about this?

**Comment by quillford** [comment]
@tarlepp that would be difficult as you would not be able to reproduce this without certain hardware

**Comment by tarlepp** [comment]
Certain hardware? Can you produce this with just basic bootstrap modals? If that happens there too, then the bug is on the bootstrap not in the bootbox.

**Comment by quillford** [comment]
I mean to say that you won't be able to access that screen without certain hardware.

**Comment by tarlepp** [comment]
Ok, can you produce that same problem with pure bootstrap modals?

**Comment by quillford** [comment]
I'll try that now with the version of bootstrap this is using.

**Comment by quillford** [comment]
@tarlepp I cannot seem to reproduce the issue with pure bootstrap modals

**Comment by tiesont** [comment]
@quillford This is most likely an issue with how you are using Bootbox. Unless you can show a stripped-down version of the code you're using, and which version of Bootbox you're using, it's going to be next to impossible to give you any meaningful help.

**Comment by quillford** [comment]
I'm using Bootbox v4.4.0. [Here](https://github.com/quillford/Mousse/blob/functional/modules/gui/screens/controlscreen/module.js#L202) is one example of my use of Bootbox.

**Comment by tiesont** [comment]
I don't really consider that a "minimal example", but looking at the source code of that project, I see some sort of "patch" file from [Jordan Schroter](https://github.com/jschr/bootstrap-modal) being loaded that is **not** necessary. It's applying styles that assume the Bootstrap 2.x markup for modals, which is not what Bootbox 4.x uses. The 4.x branch of Bootbox is built against the 3.x branch of Bootstrap, as noted in the [dependencies](http://bootboxjs.com/#dependencies) section.

You're not really getting two modals, but the styles being applied are "overlapping", for lack of a better term". That's why removing the "modal-dialog" class seems to fix the problem.

**Comment by quillford** [comment]
It does seem like modal-manager is conflicting with Bootbox. Thanks. I'll open an issue there.
