### ISSUE TITLE
Possible security issue (bootbox.js line 48)

### ISSUE THREAD

**Issue by mmunchandersen** [makeusabrew/bootbox#426]
I had my site scanned using https://www.tinfoilsecurity.com. It reports (possible false positive) a serious security issue "Password Submission via GET" in bootbox.js at line 48: <form class="bootbox-form">' .

Their suggestion:
Add a 'method' attribute to the form and set its value to 'post'. If you omit this attribute, browsers will use the default value of GET, which is insecure.

I'm unsure if this is a false positive or if this code actually present a possible security issue.

**Comment by makeusabrew** [comment]
Yes, it's a false positive since Bootbox will never actually submit the form. The line referenced doesn't look right so I'm guessing you're on an older version of Bootbox - do you know which version you're running by any chance?

In any case it's nothing to worry about, and although to be honest setting a dummy value of POST on the form would cause no harm, it seems a bit pointless just to satisfy an incorrect assessment by a third party tool. Feel free to submit a PR if it's a burning issue :)
