### ISSUE TITLE
custom dialog's buttons should be an array!

### ISSUE THREAD

**Issue by sebfindling** [makeusabrew/bootbox#431]
Hi

I find it lacks logic to have a verbose object (whose index' names aren't even used)

```js
  buttons: {
    whatever1: { label: "This label matters", ... },
    whatever2: { label: "This too", ... },
    whatever3: { label: "And his", ... },
  }
```

Would be a lot easier to write and maintain this way:

```js
  buttons: [
    { label: "This label matters", ... },
    { label: "This too", ... },
    { label: "And his", ... },
  ]
```

Or even simpler:

```js
  buttons: [
    [ 'button one', function() {} ],
    [ 'button two', function() {} ],
    [ 'button two', function() {}, 'optional-class' ],
  ]
```

**Comment by makeusabrew** [comment]
In versions prior to 3.x it was indeed an array. I can't remember why it changed to an object, but I *do* remember that there was a very good reason for changing it.

For what it's worth, you can use a label -> callback shorthand if you don't need to specify any custom attributes. Thinking about it, this may have been the primary reason behind the change. For example:
```
buttons: {
  "this label matters": function() {
    // callback code when button clicked
  }
}
```

**Comment by sebcl** [comment]
@makeusabrew oh I see; that makes sense and is *a lot* easier to write in fact. Documentation should point to his instead of the highly verbose mode :P

**Comment by makeusabrew** [comment]
Definitely. The docs still need a lot of work :)

**Comment by sebcl** [comment]
hahahaah, nice tag!

**Comment by floriancargoet** [comment]
Don't forget that [the order of object properties is not guaranteed](http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order). If it is used to order the buttons, it should be an array.

**Comment by gregpettit** [comment]
I am having an ordering issue myself that would have been a non-issue if an array was used instead of a verbose object.

I have 2 buttons that always appear, and one that conditionally appears. If I run the conditional and add the button to the "buttons" (sub)object, it appears to the right because it was the most recently added.

If I add a ```pull-right``` class to the button that needs to be on the right, it's marginally better, but then the optional button is in the middle. I want it on the left.

So, I have to make an empty button object, conditionally add my first member, then add the 2 static members. All of this in the HOPE that browser implementation preserves the order, which is not a guarantee as floriancargoet mentions.

The simpler solution would have been just to unshift the new button into the array of buttons.

Heck, I would be satisfied with an additional configuration option, which would be an array. 

```buttonOrder: ["key1", "key2", "key3"]```

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
