### ISSUE TITLE
size: 'small' not working

### ISSUE THREAD

**Issue by JoelCool** [makeusabrew/bootbox#432]
Using bootstrap v3.3.4 and bootbox v4.4.0.  Trying option {size: 'small'} has no affect.  Stepping through the code in Chrome dev tools shows no 'size' property at all in options so when it checks on line 610 nothing happens for changing the modal size.

**Comment by Saldash** [comment]
I know this is old but I had this issue very recently as well.
I simply modified the the bootbox js file to include an additional "medium" size (because i wanted a medium), and used css in my overall site.css file to apply the width to the modal based on the class added by the size property.

Works a treat :)

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
