### ISSUE TITLE
how to solve the problem? thanks!

### ISSUE THREAD

**Issue by mavict** [makeusabrew/bootbox#471]
I use bootbox in a page named son.html, and the son.html is included in a "iframe" which is a part of  "father.html" , like the following code:

\<iframe id="iframe" name="iframe" src="son.html" width="50%" height="50%"></iframe>

when bootbox alert window works in the son.html, the gray background only covers the iframe area. in other words , it is partly covered in father.html. How to make the gray background cover the whole father.html area ??

**Comment by tarlepp** [comment]
This isn't bootbox problem. Basically you're trying to do something that is not so easy to complish - because browsers will not allow modifying outer / inner dom. There is a ton of security problems. Although there are some hacks which allows you to do this.

So basically you need to trigger following code in your "father" context:

```
$('<div class="modal-backdrop"></div>').appendTo(document.body);
```

This will attach the "grey" background, source http://stackoverflow.com/questions/16487052/how-to-activate-the-bootstrap-modal-backdrop

But that question how you can trigger some father javascript functionality from your son context, that's different story. See following threads about it:
http://stackoverflow.com/questions/935127/how-to-access-parent-iframe-from-javascript
http://stackoverflow.com/questions/2161388/calling-a-parent-window-function-from-an-iframe
http://stackoverflow.com/questions/7027799/access-elements-of-parent-window-from-iframe

Closing this one now.

**Comment by mavict** [comment]
thank you very much!!
