### ISSUE TITLE
Is there an example on how to pass the result of confirm to php?

### ISSUE THREAD

**Issue by tfarina** [makeusabrew/bootbox#520]

**Comment by tiesont** [comment]
Bootbox is a jQuery plugin, meaning it runs on the client. If you want to "pass the result" to a PHP script, you need to make an AJAX request to your server. How you do that is up to you, but (since you're using jQuery anyway), I would assume you would use [the ajax() function](https://api.jquery.com/jQuery.ajax/) in some way.

So no, there is not an example.

**Comment by tfarina** [comment]
OK, I see. Thank you.
