### ISSUE TITLE
Find ID of elements

### ISSUE THREAD

**Issue by a-tz** [makeusabrew/bootbox#553]
Can you implement an attribut in order to set an ID on each element of the Bootbox please ?

**Comment by tiesont** [comment]
Not likely. What is your use case? You can access any of the Bootstrap or Bootbox elements using `find()` on an instance of a dialog. [For example](https://jsfiddle.net/wcwj6vmk/):

`bootbox.alert('Message here')
    .find('.modal-body')
    .css({ backgroundColor: 'blue' });`

**Comment by tarlepp** [comment]
+ Bootstrap itself doesn't provide ID's so not should bootbox.

**Comment by txwizard** [comment]
> Bootstrap itself doesn't provide ID's so not should bootbox.

That sounds to me like a very lame excuse.

**Comment by tiesont** [comment]
> > Bootstrap itself doesn't provide ID's so not should bootbox.
> 
> That sounds to me like a very lame excuse.

It's okay for you to think so. It's also okay for me to disagree, since I value @tarlepp and his contributions - he's one of the few fellow contributors who has maintained any presence oh these many lonely years of trying to keep the project going. 

If your contributions to this project begin and end with telling us how incompetent we are, I'd ask that you kindly find somewhere else to post your wisdom.
