### ISSUE TITLE
simple fix for the "backdrop-issue", where you can't add a class to the bootbox's backdrop

### ISSUE THREAD

**Issue by michapixel** [makeusabrew/bootbox#560]
dialog.on("**shown**.bs.modal", function() { ...

http://getbootstrap.com/javascript/#modals-events

shown.bs.modal 

This event is fired when the modal has been made visible to the user (will wait for CSS transitions to complete). If caused by a click, the clicked element is available as the relatedTarget property of the event.

One should add following styles, so the bootbox shows above a normal modal:
```
.bootbox-backdrop {
	z-index: 120001;
}
.modal.bootbox {
	z-index: 120002;
}
```

**Comment by tiesont** [comment]
What issue is this solving?

**Comment by michapixel** [comment]
see comment here:
https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L669

**Comment by tiesont** [comment]
I still don't see what this is solving - the line you mention was to add a bootbox class to the backdrop, but it's not used anywhere. @tarlepp - am I missing something here?

**Comment by michapixel** [comment]
it's needed if you have multiple modals at once

--
micha


2016-11-24 22:05 GMT+01:00 Tieson Trowbridge <notifications@github.com>:

**Comment by tiesont** [comment]
[Multiple modals are not supported by Bootstrap](http://getbootstrap.com/javascript/#callout-stacked-modals), or by native dialogs. @makeusabrew's intention is that Bootbox mimic the behavior of native dialogs as much as possible. 

If you want to demonstrate a use-case that your suggestion solves, create a working example in bootply or jsFiddle. Otherwise, I don't see this change being made.
