### ISSUE TITLE
checkboxes stay unchecked, but value submits correctly

### ISSUE THREAD

**Issue by agm1988** [makeusabrew/bootbox#581]
I am using your example with checkboxes, but when I click on checkbox it stays unchecked and when I press OK - value is sent as checkbox was checked.

bootstrap-sass (3.3.6)

jquery-rails (4.1.1)
jquery-ui-rails (5.0.5)
jquery_mobile_fa_rails (1.0.1)
jquery_mobile_rails (1.4.5)

**Comment by tiesont** [comment]
I don't see that behavior. Can you include a fiddle of some sort that reproduces the issue? Otherwise, I have to assume one or more of your other plugins are interfering - the modal generates a plain old checkbox, so if it wasn't checked you wouldn't get a value (as shown in the callback in the example here: http://bootboxjs.com/examples.html#prompt-with-checkbox).

Traditionally, jQuery UI and Bootstrap don't play well together, so that would be where I would start troubleshooting.
