### ISSUE TITLE
how to use 12 hour format

### ISSUE THREAD

**Issue by johanDev19** [makeusabrew/bootbox#587]
Hi, i will like to know how to use  12 hour format.
```
bootbox.prompt({
 title: "This is a prompt with a date input!",
 inputType: 'time',
 use24hours: false,
 callback: function (time) {
 }
})
```

> in bootstrap datepicket we use use24hours: false has params.
>i will like to know how to use 12 hours format in bootbox.js

**Comment by tiesont** [comment]
bootbox doesn't have an option for setting the hour format, in part because the [time](http://w3c.github.io/html-reference/input.time.html) input doesn't have an option for doing so - the display format is based on the browser's locale settings, and varies by vendor.

You'd have better luck using a [pattern](https://www.w3.org/TR/html5/forms.html#attr-input-pattern) with a regular text input, using the `pattern` option.
