### ISSUE TITLE
defaults not working and shown not triggering for prompt

### ISSUE THREAD

**Issue by ray73864** [makeusabrew/bootbox#614]
This is a bit of a tricky one, on all of my pages the 2 default settings I override work 100%, I have an override set on 'animate' and 'show' so that both are false.

The override is in an included file that all the pages include that way I only have to set it once, on this 1 page I have however the 'show' is not being respected, to test it I did a

```
bootbox.setDefaults({ animate: true, show: false });
```
Then clicked on the link that fires up the prompt and sure enough it animated, so I know that part is working, however the following code still shows the prompt and never triggers the 'shown' event.

```
bootbox.prompt({ title: "test", value: "My test value", callback: function(result) {  }}.on("shown.bs.modal", function(e) { console.log($(this)); });
```
When I execute that the modal still pops up, and I never see the result of $(this) in the log.

This one page is the only one with this behaviour, everywhere else I have used a prompt it works 100%.

That code is in an onClick event, the full code is:

```
$("#set_description").on("click", function(e) {
      e.preventDefault();

      bootbox.prompt({
        title: "Test Title", 
        value: "Test Value",
        callback: function(result) {
          alert(result);
        }
      }).on("shown.bs.modal", function(e) {
        var modal = $(this);
        console.log(modal);
        setTimeout(function() { modal.find("input.bootbox-input").select(); }, 200);
      });
    });
```

**Comment by ray73864** [comment]
Oddly enough, if I set it to animate (which I don't want), the 'shown' even triggers perfectly, but it still shows the modal even if I don't want it to (I prefer to manually trigger it to show).

**Comment by tiesont** [comment]
@ray73864 Sorry, I wasn't purposely ignoring this issue, it just seems like every time I intend to respond something else comes up. Are you still having this problem?

**Comment by tiesont** [comment]
This seems to happen because of this line in the prompt function:

    shouldShow = (options.show === undefined) ? true : options.show;

I can fix it with a simple change:

    shouldShow = (options.show === undefined) ? defaults.show : options.show;

This makes the prompt respect the value set in the `defaults` object, rather than assuming true if the user doesn't specify a value in the `options` object. @tarlepp @makeusabrew Would this be a breaking change?

**Comment by tiesont** [comment]
Actually, I spoke too soon. This works in _my_ fork, since I've been able to update the prompt function to use the same dialog builder as the alert and confirm functions. In this, the main repo, prompt does a lot of it's own setup, which means it mainly ignores any values set in the setDefaults() function.

@tarlepp @makeusabrew I think I can still fix this, but it definitely requires a new 4.x release - are you on board with that?

**Comment by tiesont** [comment]
With a few changes, show set to true: https://jsfiddle.net/wu697xuf/ and false: https://jsfiddle.net/wu697xuf/1/ @ray73864 - does that work for you?

**Comment by ray73864** [comment]
Will have to look tomorrow, have finished work for the day (which is where the code is being used). Do I update the bootbox.js file for these changes?

**Comment by tiesont** [comment]
@ray73864 I've pulled my BS4-compatible fork into the [v5.x](https://github.com/makeusabrew/bootbox/tree/v5.x) branch here. It works with both BS3 and BS4 (even BS2, to some degree). I've fixed this and some other outstanding bugs, if you want to give it a whirl. It _does_ change a few of the behaviors of the prompt dialog, and extracts locales out to a separate file (another reason to do a major version bump). If all you need is the English locale, you can skip loading locales.js; otherwise, load that file after bootbox.js. 

You can find a work-in-progress update to the docs [here](https://tiesont.github.io/bootbox/documentation.html).
