### ISSUE TITLE
node repositories uncentralized

### ISSUE THREAD

**Issue by shawe** [makeusabrew/bootbox#643]
Why use:
- https://www.npmjs.com/package/bootbox for 4.4.0
- https://www.npmjs.com/package/bootbox.js for 4.3.0

When the easy way is to:
- npm install bootbox.js@4.3.0
- npm install bootbox.js@4.4.0
- ...

Try it for example with BootStrap doing:
- npm install bootstrap@3.3.7
- npm install bootstrap@4.0.0-beta.2

**Comment by tiesont** [comment]
This has been more or less covered in #358 amd #579 - I can't do anything about either, since I don't have rights to either package. You could be waiting awhile to have @makeusabrew do something about it.

From what I understand, https://www.npmjs.com/package/bootbox should be the official package, but I don't know. Since I don't use NPM, it hasn't been a priority for me to get this squared away. Sorry.
