### ISSUE TITLE
HTTPS on Heroku

### ISSUE THREAD

**Issue by managuilar** [makeusabrew/bootbox#647]
Hi all, 

Congratulations for this awesome tool!

I have a question about https protocol. I deployed an application to heroku using prompt from bootbox and it does not work because of the https protocol. Does it exist any solution for this issue? 

Thanks in advance!

Manuel

**Comment by tiesont** [comment]
Bootbox doesn't do anything that would involve an HTTP or HTTPS request, so I'm not entirely sure how the protocol of your app would affect Bootbox. You might need to make sure that your CDN references, if you use them, are using HTTPS.

**Comment by jasonfb** [comment]
"it does not work because of the https protocol" -- please provide details on what you mean by "it does not work"

-- are you seeing a crash?
-- are you seeing a console error?
-- are you seeing a mixed content warning?
-- are you seeing anything else that provides clues or evidence to give more information about "it does not"

**Comment by jasonfb** [comment]
Also do yourself a favor and put SSL on your domain. Don't overpay! I recently switch to RapidSSL and have been very happy, they seem to be supported in all major browsers.

Google search "rapidssl certificate coupon" and can get ones for under $20 USD

in 2018 a real production website needs TLS, no more excuses.
