### ISSUE TITLE
Is there any way to switch places cancel and confirm buttons?

### ISSUE THREAD

**Issue by cyth319** [makeusabrew/bootbox#652]
you now, in the modal cancel button always appears first ( on the left side ), i want to switch places cancel and confirm buttons if possible. any idea?

**Comment by tiesont** [comment]
There are previous issues (#291, for instance) with suggestions for achieving this in the 4.x branch (the current master). The 5.x branch has an option for reversing the default layout (and has Bootstrap 4 support), among other changes (see #545 for what's been implemented).

**Comment by cyth319** [comment]
solution in #291  does not work for me. did you deprecated classes?

**Comment by tiesont** [comment]
Not sure what you mean by that, but no, no features have been deprecated. "does not work for me" isn't a very useful trouble-shooting statement, but regardless, switching button order is not built into the 4.x branch, nor do I plan on adding it. 

The 5.x branch will become the master at some point, since that has both Bootstrap 3 and Bootstrap 4 support, along with a couple of new options. Until then, it's up to you to figure out how to reverse the buttons.

**Comment by cyth319** [comment]
yes @tiesont, i did not add any code on purpose as my job is not immediate. 

and another little question if you please.. is there any way to get rid of one of the buttons? i tried to get rid of cancel button just like that but it did not worked

```
buttons: {
    confirm: {
        label: "yes",
     }
 },
```

**Comment by tiesont** [comment]
The confirm and prompt dialogs will always have two buttons. If you for whatever reason you want one button to not be visible, you either need to add a class to the button:

```javascript
buttons: {
    cancel: {
        className: 'hide'
    }
}
```

Or add a custom class of your own to the dialog, and then add some CSS to hide the relevant button:

```javascript
bootbox.confirm({
    // ... other options
    className: 'one-button'
})
```
and
```css
.one-button .btn-default,
.one-button .btn-secondary
{
    display: none;
}
```
