### ISSUE TITLE
bootbox.setDefaults() can not work on buttons option

### ISSUE THREAD

**Issue by badboy-huaqiao** [makeusabrew/bootbox#687]
hi, i wanted to set global button style, i use the following code, but it does not work . 

`bootbox.setDefaults({
     buttons: {
        confirm: {
            label: 'Yes',
            className: 'btn-success'
        },
        cancel: {
            label: 'No',
            className: 'btn-danger'
        }
    },
}) `

**Comment by tiesont** [comment]
The button text you can set by creating a locale and setting that in setDefaults. Settings the className values is not really an option, the way the code is written.

**Comment by badboy-huaqiao** [comment]
@tiesont thanks for your reply , can you give me a coding demo?

**Comment by tiesont** [comment]
> can you give me a coding demo?

I assume you're asking how to create a locale? That's [covered in the docs](http://bootboxjs.com/documentation.html#bb-function-addLocale), but something like this:

```javascript
bootbox.addLocale('my-locale', {
    OK: 'Yes',
    CANCEL : 'No',
    CONFIRM : 'Yes'
});

bootbox.setDefaults({ locale: 'my-locale' });
```

That would create a new locale and then update Bootbox to use it by default. You would have to override the button classes on a per-dialog basis (like [this example](http://bootboxjs.com/examples.html#also-applies-to-alert-prompt-custom%0A%0Awith-alternate-button-tex)), or update the source to override the defaults we use, since there isn't currently an option for that. 

You could also set a value for `className`, and then add your own CSS to override `btn-primary` and `btn-default`, which is probably the "cleanest" option. So, building off of the previous example:

```CSS
.modal.red-green-buttons .btn-primary
{
    background-color: #0c0;
    color: #fff;
}

.modal.red-green-buttons .btn-default
{
    background-color: #c00;
    color: #fff;
}
```
This would be the result: https://jsfiddle.net/8tjfanw5/1/

**Comment by badboy-huaqiao** [comment]
@tiesont ,yeah! it's just that i'm looking for, so i do not have to set the button in every dialog and reduce the amount of code, thanks very much for you reply , Awesome! 👍 😊

**Comment by tiesont** [comment]
If you are (or can switch to) using [Sass](https://sass-lang.com/), you can actually do something like:

```css
.modal
{
    &.red-green-buttons
    {
        .btn-primary
        {
            @extend .btn-success;
        }

        .btn-default
        {
            @extend .btn-danger;
        }
    }
}
```

This has the advantage of pulling in all of the rules for the success and danger buttons - if you pay attention to the fiddle, the buttons have a few styles that I didn't bother to override.

**Comment by badboy-huaqiao** [comment]
@tiesont ok, thanks, i didn't use Sass or Less, but it may be used for others.😊
