### ISSUE TITLE
Callback function global variable value updation is not reflecting in the main code

### ISSUE THREAD

**Issue by jef234** [makeusabrew/bootbox#706]
Hey Guys

Great dialogue framework guys. however, I am facing this issue.

Inside the Callback function, global variable value updation is not reflecting in the main code.

Code:
```
//main javascript code
var a = "";
..
bootbox.dialog({
...
buttons: {
                ok: {
                    label: "OK",
                    className: '',
                    callback: function () {
                    ...
                    //update a global variable
                   a = "update";
                    ... }
                  }
              }
});
..
//main javascript code
//using same global variable
console.log(a); //returns null

```
Google Chrome: 73.0.3683.103 (Official Build) (32-bit)
Windows 10 Enterprise
jquery@3.4.0
bootstrap@4.3.1
bootbox@5.1.3

**Comment by tiesont** [comment]
As noted in the documentation, the various dialog functions are asynchronous. So, what is likely happening is the your `console.log(a);` is being called while the dialog is still open. If that doesn't seem to be the case for you locally, please create a more complete example (a jsFiddle would be lovely) and I'll see if I can duplicate what you're seeing.

**Comment by jef234** [comment]
So bootbox is an asynchronous function. 
Is there a way in which I can wait for bootbox to execute completely and then continue with my main javascript code?

**Comment by tiesont** [comment]
> Is there a way in which I can wait for bootbox to execute completely

Not really. Bootbox is mainly just a wrapper around Bootstrap's modal.js code, which itself is just positioning an HTML element above the rest of the page content. 

The closest you get with Bootbox is to move the rest of your code into the dialog's callback function (or wrap your code in a function and call that in the callback).

If you're using a version of Chromium (Chrome, Opera, and eventually Edge) or Mozilla (Firefox et al) which have support for the element enabled, there _is_ the [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element, which is the only element I know of that can be styled _and_ block the thread of execution (what the native alert, prompt, and confirm do). [It's not supported by default](https://caniuse.com/#feat=dialog), though, which is why we (and I assume Bootstrap) don't use it.

**Comment by jef234** [comment]
Alright, < dialog > is a good way to implement
Thanks @tiesont
