### ISSUE TITLE
Radio buttons not displaying properly

### ISSUE THREAD

**Issue by Alephel** [makeusabrew/bootbox#709]
Hello,

Please help me with what may indeed be a rookie question?

Somehow I am not able to get the radio buttons to display properly even with copy and past of the provided sample. See screenshot below

Thanks

![Screen Shot 2019-06-18 at 1 52 29 PM](https://user-images.githubusercontent.com/51819333/59683787-b48ee700-91d0-11e9-870e-7abe2d01d21b.png)

**Comment by tiesont** [comment]
We'll need to see some code to even guess at what the issue is. As a wild guess, I assume whatever theme you're using has styles to hide the radio buttons and replace them with custom versions (similar to the [built-in custom inputs](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios-1)), and that theme doesn't take into account elements being added/shown after page load.

**Comment by Alephel** [comment]
Resolved, thanks
