### ISSUE TITLE
centerVertical doesn't work on prompts

### ISSUE THREAD

**Issue by ray73864** [makeusabrew/bootbox#711]
I'm not sure if this is an oversight or maybe i'm just missing something, but for some reason I can't use 'centerVertical' on a prompt.

It works 100% on dialogs and pretty sure alert boxes, but I can't get it to work on prompts at all.

I'm using it by doing:

```
bootbox.prompt({
  centerVertical: true,
  title: "My Test Title",
  callback: function(result) {  }
}).modal("show");
```

Just made sure i'm using the latest version (Was previously on 5.0.0 now on 5.1.3) and it is still not working.

**Comment by tiesont** [comment]
What version of Bootstrap are you using?

**Comment by ray73864** [comment]
Pretty sure I said that at the end :) But anyway, was on 5.0.0, now currently on 5.1.3.

**Comment by tiesont** [comment]
**Bootstrap**, not Bootbox. It helps me to try to reproduce what you're seeing to use the same Bootstrap version.

**Comment by tiesont** [comment]
Just added an example of a vertically-centered prompt (see http://bootboxjs.com/examples.html#prompt-centerVertical) and added a couple of unit tests. I can't reproduce what you're seeing, at the moment.

**Comment by ray73864** [comment]
Sorry.

Bootstrap version is 4.3.1.

**Comment by tiesont** [comment]
I have a project with the same Bootstrap version and v5.1.0, and it works as intended. I'll update it and check, but I don't think this is something on our end. 

One thing to check is to make sure your JS references have been updated, although `modal-dialog-centered` has been around since Beta 3 of Bootstrap 4, so you'd have to be way out-of-sync for that to be the issue. Otherwise, the only other obvious suggestion is to make sure you've cleared your browser cache, if you're using some sort of build system.
