### ISSUE TITLE
Cancel button doesn't close the modal, bootbox v4.4.0

### ISSUE THREAD

**Issue by deXterbed** [makeusabrew/bootbox#769]
I am using `react v15.5.4` & `bootstrap v3.3.5`, and here's the JSX snippet:

```
<td><a onClick={() => {
  bootbox.confirm('Are you sure you want to delete this order?', result => result && dispatch(deleteOrder(id, 
  order.toLowerCase())))
}}><i className="fa fa-trash left-icon"></i></a></td>
```

**Comment by tiesont** [comment]
Sorry, haven't really had much of a reason to transition to the arrow-style functions - I assume this is a timing issue, but I'm not sure when I'd be able to get around to verifying this. I'm also not all that keen on maintaining the v4.x branch at this point, since Bootstrap 3 is getting pretty close to EOL at this point.

If you can share a jsFiddle or similar with a test case set up, I'd be willing to take a look, but I can't say when I'd be able to get this.
