### ISSUE TITLE
Dialog Modals reset to the bottom after opening

### ISSUE THREAD

**Issue by eribean** [makeusabrew/bootbox#779]
This isn't necessarily an issue but unexpected behavior. When a dialog modal with buttons is opened, the animation brings the modal to the top but is subsequently reset to be referenced from the bottom (shows buttons and not title). 

To replicate this, go to the [examples](http://bootboxjs.com/examples.html) page, reset the viewer to be small (height around 150 px) and run the last example "Custom dialog, with buttons and callbacks".  The buttons are shown but the title is hidden.

**Comment by tiesont** [comment]
Not sure what you mean by "reset". I'd need to see an actual example, including which versions of Bootbox and Bootstrap you're using.

**Comment by eribean** [comment]
Are you unable to replicate it on your examples page via my description?

**Comment by tarlepp** [comment]
ok so I think that htis is the current result:
![image](https://user-images.githubusercontent.com/595561/106202643-db8e0700-61c2-11eb-9e39-80aba6896b2c.png)

and you would like to see:
![image](https://user-images.githubusercontent.com/595561/106202681-e5176f00-61c2-11eb-92cd-d06170fd0f43.png)


I think that use case isn't so common - but if you see that is important, I would recommend you to create PR that fixes that.

**Comment by eribean** [comment]
Here is an exampe ![img](https://girthphotos.s3-us-west-2.amazonaws.com/Screenshot+from+2021-01-28+16-41-53.png)

**Comment by eribean** [comment]
Ahh, you beat me to it. Yes, the other dialog boxes look like the second image @tarlepp. Is there an option that I just don't know about?

**Comment by tiesont** [comment]
As I noted

> Not sure what you mean by "reset".

Bootbox doesn't handle any changes to the viewport, itself. Bootstrap has guidance on responding to viewport changes, if that's what you mean. 

What you've added in you most recent comment is what I would expect to see. Bootstrap modals are fixed-positioned divs, and that position is calculated when the modal is shown. [modalHandleUpdate](https://getbootstrap.com/docs/4.6/components/modal/#modalhandleupdate) _might_ correct that, but I don't know.

**Comment by eribean** [comment]
@tiesont , This behavior doesn't occur if I use a prompt dialog. It gets shown with the title first?

**Comment by eribean** [comment]
@tarlepp This occurs on mobile quite frequently if the modal is long. I just used that example to demonstrate it.

**Comment by tiesont** [comment]
@eribean Again, an example would help. "Go to the examples page and do _x_" isn't enough. Unless @tarlepp has time to dig into reproducing what you're describing. I, unfortunately, don't.

**Comment by eribean** [comment]
[working example](https://codepen.io/Eribean/pen/ExNxYqB)

**Comment by eribean** [comment]
The error occurs for dialog modals that use buttons with labels ```ok``` or ```confirm```. I didn't dig much deeper and I don't anything needs to be fixed, it would be nice to add a quick blurb to the documentation page suggesting not to use protected names in dialog modals. Will close issue.

**Comment by tiesont** [comment]
The alert, confirm, and prompt functions all use the dialog function to build their modals - we're not doing anything special with regards to positioning or sizing of the dialog. The height of those dialogs are likely to be less than a custom dialog, just because they have very targeted uses (and limit what can be displayed inside them, in the case of the prompt dialog). 

The reason you see different behavior for the first modal in your example is due to this line: https://github.com/makeusabrew/bootbox/blob/e3de4ea6342a245530a291b4909cc796219b556a/bootbox.js#L1148

Basically, the "accept" button is focused, so that a user can just hit their "Enter" key to dismiss/accept the modal. On a viewport shorter than the modal, that means that the page is scrolled. We automatically apply our `bootbox-accept` class to any button with the 'ok' or 'confirm' key, so in that respect, yes, using either of those is different than using any other random name.

If you want your modal header and buttons to always be visible, Bootstrap has a class that will automatically add a scrollbar to the modal body if the modal is taller than the viewport. You can enable that by setting the `scrollable` option to `true`.

**Comment by Zoopme** [comment]
Hi all,
This issue was already mentioned various times: #260, #576 #596.
The know solution is to shut down the event triggering this behaviour by using `.off("shown.bs.modal")`
